name: Repository Request
description: Use this template to request a new repository.
title: "[Request] New Repository"
labels: repo-request
body:
  - type: input
    id: name
    attributes:
      label: Repository Name
      description: "Enter the name of the repository (kebab-case, e.g., my-repo)"
      placeholder: "my-repo"
      required: true

  - type: dropdown
    id: department
    attributes:
      label: Department
      description: "Select the department prefix for the repository"
      options:
        - frontend
        - backend
        - devops
        - qa
      required: true
